# Generated by Django 4.1 on 2022-11-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=10, default=0, max_digits=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='locations',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='end',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='start',
        ),
        migrations.AddField(
            model_name='locations',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
