# Generated by Django 4.1 on 2022-11-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_locationdist_remove_locations_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
